/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz_java;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Run the Lesson2 quiz
        new Lesson2().run();
    }
}
